/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.11.0                                              */
/*  Date (dd.mm.yyyy): 30. 6.2022   Time (hh:mm): 15:34                        */
/*******************************************************************************/


#ifndef _BACKPMANV3_DISPLAY_1_RESOURCES_H_
#define _BACKPMANV3_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

#if !defined(GX_UTF8_SUPPORT)
#error "The symbol GX_UTF8_SUPPORT must be defined to support the Studio project settings".
#endif
#if !defined(GX_EXTENDED_UNICODE_SUPPORT)
#error "The symbol GX_EXTENDED_UNICODE_SUPPORT must be defined to support the Studio project settings".
#endif

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 240
#define DISPLAY_1_Y_RESOLUTION 240
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_RUSSIAN 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_BLACK 29
#define GX_COLOR_ID_BLUE 30
#define GX_COLOR_ID_GREEN 31
#define GX_COLOR_ID_RED 32
#define GX_COLOR_ID_CIAN 33
#define GX_COLOR_ID_DARK_BLUE 34
#define GX_COLOR_ID_YELLOW 35
#define GX_COLOR_ID_WHITE 36
#define GX_COLOR_ID_GRAY 37
#define GX_COLOR_ID_DARK_YELLOW 38
#define GX_COLOR_ID_TEMPERATURE 39
#define DISPLAY_1_COLOR_TABLE_SIZE 40

/* Font ID definitions                                                         */

#define GX_FONT_ID_DSEG7CLASSICMINI_BOLDITALIC_30PX 4
#define GX_FONT_ID_VERA_20PX 5
#define GX_FONT_ID_NOTOSANSCJKSC_REGULAR_20PX 6
#define GX_FONT_ID_DSEG7CLASSICMINI_BOLDITALIC_20PX 7
#define GX_FONT_ID_NOTOSANSCJKSC_REGULAR_30PX 8
#define DISPLAY_1_FONT_TABLE_SIZE 9

/* Pixelmap ID definitions                                                     */

#define DISPLAY_1_PIXELMAP_TABLE_SIZE 5

/* String Ids                                                                  */

#define GX_STRING_ID_STR1 1
#define GX_STRING_ID_STR2 2
#define GX_STRING_ID_TXT_U_INP 3
#define GX_STRING_ID_TXT_U_OUT 4
#define GX_STRING_ID_STR3 5
#define GX_STRING_ID_STR4 6
#define GX_STRING_ID_STR5 7
#define GX_STRING_ID_STR6 8
#define GX_STRING_ID_STR7 9
#define GX_STRING_ID_STR8 10
#define GX_STRING_ID_TXT_I_OUT 11
#define GX_STRING_ID_TXT_LOSSES 12
#define GX_STRING_ID_TXT_EFFICIENCY 13
#define GX_STRING_ID_STR0 14
#define GX_STRING_ID_STR10 15
#define GX_STRING_ID_STR11 16
#define GX_STRING_ID_TXT_TEMPER 17
#define DISPLAY_1_STRING_TABLE_SIZE 18

#endif                                       /* sentry                         */
