/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.12.0                                              */
/*  Date (dd.mm.yyyy):  6.10.2022   Time (hh:mm): 16:25                        */
/*******************************************************************************/


#ifndef _BACKPMANV3_DISPLAY_1_RESOURCES_H_
#define _BACKPMANV3_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

#if !defined(GX_UTF8_SUPPORT)
#error "The symbol GX_UTF8_SUPPORT must be defined to support the Studio project settings".
#endif
#if !defined(GX_EXTENDED_UNICODE_SUPPORT)
#error "The symbol GX_EXTENDED_UNICODE_SUPPORT must be defined to support the Studio project settings".
#endif

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 240
#define DISPLAY_1_Y_RESOLUTION 240
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_RUSSIAN 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_BLACK 29
#define GX_COLOR_ID_BLUE 30
#define GX_COLOR_ID_GREEN 31
#define GX_COLOR_ID_RED 32
#define GX_COLOR_ID_CIAN 33
#define GX_COLOR_ID_DARK_BLUE 34
#define GX_COLOR_ID_YELLOW 35
#define GX_COLOR_ID_WHITE 36
#define GX_COLOR_ID_GRAY 37
#define GX_COLOR_ID_DARK_YELLOW 38
#define GX_COLOR_ID_TEMPERATURE 39
#define DISPLAY_1_COLOR_TABLE_SIZE 40

/* Font ID definitions                                                         */

#define GX_FONT_ID_VERA_20PX 4
#define GX_FONT_ID_NOTOSANSCJKSC_20 5
#define GX_FONT_ID_NOTOSANSCJKSC_30 6
#define GX_FONT_ID_NOTOSANSCJKSC_12 7
#define DISPLAY_1_FONT_TABLE_SIZE 8

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_BLUEDOT 5
#define GX_PIXELMAP_ID_BROWNDOT 6
#define GX_PIXELMAP_ID_CYANDOT 7
#define GX_PIXELMAP_ID_GREENDOT 8
#define GX_PIXELMAP_ID_LIGHTBLUEDOT 9
#define GX_PIXELMAP_ID_REDDOT 10
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 11

/* String Ids                                                                  */

#define GX_STRING_ID_STR1 1
#define GX_STRING_ID_STR2 2
#define GX_STRING_ID_TXT_U_INP 3
#define GX_STRING_ID_TXT_U_OUT 4
#define GX_STRING_ID_STR3 5
#define GX_STRING_ID_STR4 6
#define GX_STRING_ID_STR5 7
#define GX_STRING_ID_STR6 8
#define GX_STRING_ID_STR7 9
#define GX_STRING_ID_STR8 10
#define GX_STRING_ID_TXT_I_OUT 11
#define GX_STRING_ID_TXT_LOSSES 12
#define GX_STRING_ID_TXT_EFFICIENCY 13
#define GX_STRING_ID_STR0 14
#define GX_STRING_ID_STR10 15
#define GX_STRING_ID_STR11 16
#define GX_STRING_ID_TXT_TEMPER 17
#define GX_STRING_ID_STRING_1 18
#define GX_STRING_ID_STRING_2 19
#define GX_STRING_ID_STRING_3 20
#define GX_STRING_ID_STRING_4 21
#define GX_STRING_ID_STRING_5 22
#define GX_STRING_ID_STRING_6 23
#define GX_STRING_ID_STRING_7 24
#define GX_STRING_ID_STRING_8 25
#define GX_STRING_ID_STRING_9 26
#define GX_STRING_ID_STRING_10 27
#define GX_STRING_ID_STRING_11 28
#define GX_STRING_ID_STRING_12 29
#define GX_STRING_ID_STRING_13 30
#define GX_STRING_ID_STRING_14 31
#define GX_STRING_ID_STRING_15 32
#define GX_STRING_ID_STRING_16 33
#define GX_STRING_ID_STRING_17 34
#define GX_STRING_ID_STRING_18 35
#define GX_STRING_ID_STRING_19 36
#define GX_STRING_ID_STRING_20 37
#define GX_STRING_ID_STRING_21 38
#define GX_STRING_ID_STRING_22 39
#define GX_STRING_ID_STRING_23 40
#define GX_STRING_ID_STRING_24 41
#define GX_STRING_ID_STRING_25 42
#define GX_STRING_ID_STRING_26 43
#define GX_STRING_ID_STRING_27 44
#define GX_STRING_ID_STRING_28 45
#define GX_STRING_ID_STRING_29 46
#define GX_STRING_ID_STRING_30 47
#define GX_STRING_ID_STRING_31 48
#define GX_STRING_ID_STRING_32 49
#define GX_STRING_ID_STRING_33 50
#define GX_STRING_ID_STRING_34 51
#define GX_STRING_ID_STRING_35 52
#define GX_STRING_ID_STRING_36 53
#define GX_STRING_ID_STRING_37 54
#define GX_STRING_ID_STRING_38 55
#define GX_STRING_ID_STRING_39 56
#define GX_STRING_ID_STRING_40 57
#define GX_STRING_ID_STRING_41 58
#define GX_STRING_ID_STRING_42 59
#define GX_STRING_ID_STRING_43 60
#define GX_STRING_ID_STRING_44 61
#define GX_STRING_ID_STRING_45 62
#define GX_STRING_ID_STRING_46 63
#define GX_STRING_ID_STRING_47 64
#define GX_STRING_ID_STRING_48 65
#define GX_STRING_ID_STRING_49 66
#define GX_STRING_ID_STRING_50 67
#define GX_STRING_ID_STRING_51 68
#define GX_STRING_ID_STRING_52 69
#define GX_STRING_ID_STRING_53 70
#define GX_STRING_ID_STRING_54 71
#define GX_STRING_ID_STRING_55 72
#define GX_STRING_ID_STRING_56 73
#define GX_STRING_ID_STRING_57 74
#define GX_STRING_ID_STRING_58 75
#define GX_STRING_ID_STRING_59 76
#define GX_STRING_ID_STRING_60 77
#define GX_STRING_ID_STRING_61 78
#define GX_STRING_ID_STRING_62 79
#define GX_STRING_ID_STRING_63 80
#define GX_STRING_ID_STRING_64 81
#define GX_STRING_ID_STRING_65 82
#define GX_STRING_ID_STRING_66 83
#define GX_STRING_ID_STRING_67 84
#define GX_STRING_ID_STRING_68 85
#define GX_STRING_ID_STRING_69 86
#define GX_STRING_ID_STRING_70 87
#define GX_STRING_ID_STRING_71 88
#define GX_STRING_ID_STRING_72 89
#define GX_STRING_ID_STRING_73 90
#define GX_STRING_ID_STRING_74 91
#define GX_STRING_ID_STRING_75 92
#define GX_STRING_ID_STRING_76 93
#define GX_STRING_ID_STRING_77 94
#define GX_STRING_ID_STRING_78 95
#define GX_STRING_ID_STRING_79 96
#define GX_STRING_ID_STRING_80 97
#define GX_STRING_ID_STRING_81 98
#define GX_STRING_ID_STRING_82 99
#define GX_STRING_ID_STRING_83 100
#define GX_STRING_ID_STRING_84 101
#define GX_STRING_ID_STRING_85 102
#define GX_STRING_ID_STRING_86 103
#define GX_STRING_ID_STRING_87 104
#define GX_STRING_ID_STRING_88 105
#define GX_STRING_ID_STRING_89 106
#define GX_STRING_ID_STRING_90 107
#define GX_STRING_ID_STRING_91 108
#define GX_STRING_ID_STRING_92 109
#define GX_STRING_ID_STRING_93 110
#define GX_STRING_ID_STRING_94 111
#define GX_STRING_ID_STRING_95 112
#define GX_STRING_ID_STRING_96 113
#define GX_STRING_ID_STRING_97 114
#define GX_STRING_ID_STRING_98 115
#define GX_STRING_ID_STRING_99 116
#define GX_STRING_ID_STRING_100 117
#define GX_STRING_ID_STRING_101 118
#define GX_STRING_ID_STRING_102 119
#define GX_STRING_ID_STRING_103 120
#define GX_STRING_ID_STRING_104 121
#define DISPLAY_1_STRING_TABLE_SIZE 122

#endif                                       /* sentry                         */
