#include "App.h"
#include "freemaster_cfg.h"
#include "freemaster.h"
#include "freemaster_tsa.h"

const T_parmenu parmenu[9]=
{
  {BKMAN3R1_0,BKMAN3R1_main,"Parameters and settings","PARAMETERS", -1},//  Основная категория
  {BKMAN3R1_main,BKMAN3R1_General,"General settings","GENERAL SETTINGS", -1},//  
  {BKMAN3R1_main,BKMAN3R1_RNDIS,"RNDIS device mode settings","RNDIS SETTINGS", -1},//  
  {BKMAN3R1_main,BKMAN3R1_CDC_ECM,"CDC ECM host mode settings","ECM SETTINGS", -1},//  
  {BKMAN3R1_main,BKMAN3R1_WEB_SERVER,"Web server settings","WEB SETTINGS", -1},//  
  {BKMAN3R1_main,BKMAN3R1_FTP_SERVER,"FTP server settings","FTP SETTINGS", -1},//  
  {BKMAN3R1_main,BKMAN3R1_CALIBRATION,"Calibration parameters","CALIBR", -1},//  
  {BKMAN3R1_main,BKMAN3R1_FTP_CLIENT,"FTP client task settings","FTP CLIENT SETTINGS", -1},//  
  {BKMAN3R1_main,BKMAN3R1_MQTT,"MQTT client task settings","MQTT CLIENT SETTINGS", -1},//  
};


const T_work_params dwvar[32]=
{
  {
    "psrc_current_offset",
    "Power source current offset",
    "-",
    (void*)&wvar.psrc_current_offset,
    tfloat,
    0,
    -1,
    1,
    0,
    BKMAN3R1_CALIBRATION,
    "",
    "%0.4f",
    0,
    sizeof(wvar.psrc_current_offset),
    1,
    0,
  },
  {
    "acc_current_offset",
    "Accumulator current offset (A)",
    "-",
    (void*)&wvar.acc_current_offset,
    tfloat,
    0,
    -1,
    1,
    0,
    BKMAN3R1_CALIBRATION,
    "",
    "%0.4f",
    0,
    sizeof(wvar.acc_current_offset),
    2,
    0,
  },
  {
    "load_current_offset",
    "Load current offset (A)",
    "-",
    (void*)&wvar.load_current_offset,
    tfloat,
    0,
    -1,
    1,
    0,
    BKMAN3R1_CALIBRATION,
    "",
    "%04f",
    0,
    sizeof(wvar.load_current_offset),
    3,
    0,
  },
  {
    "default_ip_addr",
    "Default IP address",
    "DEFIPAD",
    (void*)&wvar.default_ip_addr,
    tstring,
    0,
    0,
    0,
    0,
    BKMAN3R1_CDC_ECM,
    "192.168.1.1",
    "%s",
    0,
    sizeof(wvar.default_ip_addr),
    1,
    4,
  },
  {
    "default_net_mask",
    "Default network mask ",
    "DEFNTMS",
    (void*)&wvar.default_net_mask,
    tstring,
    0,
    0,
    0,
    0,
    BKMAN3R1_CDC_ECM,
    "255.255.255.0",
    "%s",
    0,
    sizeof(wvar.default_net_mask),
    2,
    4,
  },
  {
    "default_gateway_addr",
    "Default gateway address",
    "DEFGATE",
    (void*)&wvar.default_gateway_addr,
    tstring,
    0,
    0,
    0,
    0,
    BKMAN3R1_CDC_ECM,
    "192.168.1.254",
    "%s",
    0,
    sizeof(wvar.default_gateway_addr),
    3,
    4,
  },
  {
    "en_dhcp_client",
    "Enable DHCP client (0-No, 1-Yes)",
    "ENDHCPC",
    (void*)&wvar.en_dhcp_client,
    tint8u,
    1,
    0,
    1,
    0,
    BKMAN3R1_CDC_ECM,
    "",
    "%d",
    0,
    sizeof(wvar.en_dhcp_client),
    4,
    1,
  },
  {
    "this_host_name",
    "This device host name",
    "HOSTNAM",
    (void*)&wvar.this_host_name,
    tstring,
    0,
    0,
    0,
    0,
    BKMAN3R1_CDC_ECM,
    "host1",
    "%s",
    0,
    sizeof(wvar.this_host_name),
    5,
    0,
  },
  {
    "en_ftp_client",
    "Enable FTP client task",
    "-",
    (void*)&wvar.en_ftp_client,
    tint8u,
    0,
    0,
    1,
    0,
    BKMAN3R1_FTP_CLIENT,
    "",
    "%d",
    0,
    sizeof(wvar.en_ftp_client),
    1,
    1,
  },
  {
    "max_scv_file_sz",
    "Max .csv file size (byte)",
    "-",
    (void*)&wvar.max_scv_file_sz,
    tint32u,
    100000,
    1000,
    1000000000,
    0,
    BKMAN3R1_FTP_CLIENT,
    "",
    "%d",
    0,
    sizeof(wvar.max_scv_file_sz),
    2,
    0,
  },
  {
    "ftp_client_server_adress",
    "FTP server address",
    "-",
    (void*)&wvar.ftp_client_server_adress,
    tstring,
    0,
    0,
    0,
    0,
    BKMAN3R1_FTP_CLIENT,
    "192.168.3.2",
    "%s",
    0,
    sizeof(wvar.ftp_client_server_adress),
    3,
    4,
  },
  {
    "ftp_client_server_login",
    "FTP server login",
    "-",
    (void*)&wvar.ftp_client_server_login,
    tstring,
    0,
    0,
    0,
    0,
    BKMAN3R1_FTP_CLIENT,
    "login",
    "%s",
    0,
    sizeof(wvar.ftp_client_server_login),
    4,
    0,
  },
  {
    "ftp_client_server_pass",
    "FTP server password",
    "-",
    (void*)&wvar.ftp_client_server_pass,
    tstring,
    0,
    0,
    0,
    0,
    BKMAN3R1_FTP_CLIENT,
    "pass",
    "%s",
    0,
    sizeof(wvar.ftp_client_server_pass),
    5,
    0,
  },
  {
    "enable_ftp_server",
    "Enable FTP server",
    "-",
    (void*)&wvar.enable_ftp_server,
    tint8u,
    1,
    0,
    1,
    0,
    BKMAN3R1_FTP_SERVER,
    "",
    "%d",
    0,
    sizeof(wvar.enable_ftp_server),
    1,
    1,
  },
  {
    "ftp_serv_login",
    "Login",
    "-",
    (void*)&wvar.ftp_serv_login,
    tstring,
    0,
    0,
    0,
    0,
    BKMAN3R1_FTP_SERVER,
    "ftp_login",
    "%s",
    0,
    sizeof(wvar.ftp_serv_login),
    2,
    0,
  },
  {
    "ftp_serv_password",
    "Password ",
    "-",
    (void*)&wvar.ftp_serv_password,
    tstring,
    0,
    0,
    0,
    0,
    BKMAN3R1_FTP_SERVER,
    "ftp_pass",
    "%s",
    0,
    sizeof(wvar.ftp_serv_password),
    3,
    0,
  },
  {
    "name",
    "Product  name",
    "-",
    (void*)&wvar.name,
    tstring,
    0,
    0,
    0,
    0,
    BKMAN3R1_General,
    "BKMAN3R1",
    "%s",
    0,
    sizeof(wvar.name),
    1,
    0,
  },
  {
    "ver",
    "Firmware version",
    "-",
    (void*)&wvar.ver,
    tstring,
    0,
    0,
    0,
    0,
    BKMAN3R1_General,
    "1.0",
    "%s",
    0,
    sizeof(wvar.ver),
    2,
    0,
  },
  {
    "can_node_number",
    "CAN node number",
    "-",
    (void*)&wvar.can_node_number,
    tint8u,
    1,
    1,
    255,
    0,
    BKMAN3R1_General,
    "",
    "%d",
    0,
    sizeof(wvar.can_node_number),
    3,
    0,
  },
  {
    "usb_mode",
    "USB mode (0- RNDIS & VCOM device, 1- CDC ECM host)",
    "-",
    (void*)&wvar.usb_mode,
    tint8u,
    1,
    0,
    1,
    0,
    BKMAN3R1_General,
    "",
    "%d",
    0,
    sizeof(wvar.usb_mode),
    4,
    3,
  },
  {
    "en_freemaster",
    "Enable FreeMaster protocol",
    "-",
    (void*)&wvar.en_freemaster,
    tint8u,
    1,
    0,
    1,
    0,
    BKMAN3R1_General,
    "",
    "%d",
    0,
    sizeof(wvar.en_freemaster),
    5,
    1,
  },
  {
    "en_matlab",
    "Enable MATLAB connection",
    "-",
    (void*)&wvar.en_matlab,
    tint8u,
    1,
    0,
    1,
    0,
    BKMAN3R1_General,
    "",
    "%d",
    0,
    sizeof(wvar.en_matlab),
    6,
    1,
  },
  {
    "mqtt_enable",
    "Enable MQTT client ",
    "-",
    (void*)&wvar.mqtt_enable,
    tint8u,
    0,
    0,
    1,
    0,
    BKMAN3R1_MQTT,
    "",
    "%d",
    0,
    sizeof(wvar.mqtt_enable),
    1,
    1,
  },
  {
    "mqtt_client_id",
    "Client ID",
    "-",
    (void*)&wvar.mqtt_client_id,
    tstring,
    0,
    0,
    0,
    0,
    BKMAN3R1_MQTT,
    "Client1",
    "%s",
    0,
    sizeof(wvar.mqtt_client_id),
    2,
    0,
  },
  {
    "mqtt_server_ip",
    "MQTT server IP address",
    "-",
    (void*)&wvar.mqtt_server_ip,
    tstring,
    0,
    0,
    0,
    0,
    BKMAN3R1_MQTT,
    "192.168.3.2",
    "%s",
    0,
    sizeof(wvar.mqtt_server_ip),
    3,
    0,
  },
  {
    "mqtt_server_port",
    "MQTT server port number",
    "-",
    (void*)&wvar.mqtt_server_port,
    tint16u,
    1883,
    0,
    65535,
    0,
    BKMAN3R1_MQTT,
    "",
    "%d",
    0,
    sizeof(wvar.mqtt_server_port),
    4,
    0,
  },
  {
    "mqtt_user_name",
    "User name",
    "-",
    (void*)&wvar.mqtt_user_name,
    tstring,
    0,
    0,
    0,
    0,
    BKMAN3R1_MQTT,
    "user",
    "%s",
    0,
    sizeof(wvar.mqtt_user_name),
    5,
    0,
  },
  {
    "mqtt_password",
    "User password",
    "-",
    (void*)&wvar.mqtt_password,
    tstring,
    0,
    0,
    0,
    0,
    BKMAN3R1_MQTT,
    "pass",
    "%s",
    0,
    sizeof(wvar.mqtt_password),
    6,
    0,
  },
  {
    "rndis_config",
    "RNDIS interface configuration (0-Win home net, 1 - DHCP server)",
    "-",
    (void*)&wvar.rndis_config,
    tint8u,
    1,
    0,
    1,
    0,
    BKMAN3R1_RNDIS,
    "",
    "%d",
    0,
    sizeof(wvar.rndis_config),
    1,
    2,
  },
  {
    "enable_HTTP_server",
    "Enable WEB server",
    "-",
    (void*)&wvar.enable_HTTP_server,
    tint8u,
    1,
    0,
    1,
    0,
    BKMAN3R1_WEB_SERVER,
    "",
    "%d",
    0,
    sizeof(wvar.enable_HTTP_server),
    2,
    1,
  },
  {
    "enable_HTTPS",
    "Enable_HTTPS",
    "-",
    (void*)&wvar.enable_HTTPS,
    tint8u,
    0,
    0,
    1,
    0,
    BKMAN3R1_WEB_SERVER,
    "",
    "%d",
    0,
    sizeof(wvar.enable_HTTPS),
    3,
    1,
  },
  {
    "HTTP_server_password",
    "HTTP server pasword",
    "-",
    (void*)&wvar.HTTP_server_password,
    tstring,
    0,
    0,
    0,
    0,
    BKMAN3R1_WEB_SERVER,
    "123456789",
    "%s",
    0,
    sizeof(wvar.HTTP_server_password),
    4,
    0,
  },
};
 
 
// Selector description:  Выбор между Yes и No
static const T_selector_items selector_1[2] = 
{
  {0, "No", 0},
  {1, "Yes", 1},
};
 
// Selector description:  Confuguration of RNDIS interface
static const T_selector_items selector_2[2] = 
{
  {0, "Windows home network ", -1},
  {1, "Preconfigured DHCP server", -1},
};
 
// Selector description:  Режим работы USB интерфеса
static const T_selector_items selector_3[2] = 
{
  {0, "Device", -1},
  {1, "Host", -1},
};
 
const T_selectors_list selectors_list[5] = 
{
  {"string"            , 0    , 0             },
  {"binary"            , 2    , selector_1    },
  {"rndis_config"      , 2    , selector_2    },
  {"usb_mode"          , 2    , selector_3    },
  {"ip_addr"           , 0    , 0             },
};
 
