#include "App.h"
#include "freemaster_cfg.h"
#include "freemaster.h"
#include "freemaster_tsa.h"


FMSTR_TSA_TABLE_BEGIN(app_vars)
FMSTR_TSA_RW_VAR(g_cpu_usage                            ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(g_cpu_usage_fp                         ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.ain1                           ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.ain2                           ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.ain3                           ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.ain4                           ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.vref165                        ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.acc_i                          ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.psrc_i                         ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.load_i                         ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.acc_v                          ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.psrc_v                         ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.load_v                         ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.sys_v                          ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.ref_v                          ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.cpu_temp                       ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.t_sens                         ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.psrc_pwr                       ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.acc_pwr                        ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.charge_loss                    ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.charge_efficiency              ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.flt_acc_i_uncal                ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.flt_acc_i                      ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.flt_psrc_i_uncal               ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.flt_psrc_i                     ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.flt_load_i_uncal               ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.flt_load_i                     ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.flt_acc_v                      ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.flt_psrc_v                     ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.flt_load_v                     ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.flt_sys_v                      ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.flt_ref_v                      ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(fp_meas.charge                         ,FMSTR_TSA_DOUBLE)


FMSTR_TSA_RW_VAR(enc_cbl.encoder_counter                ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(enc_cbl.curr_enc_a_smpl                ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(enc_cbl.curr_enc_b_smpl                ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(enc_cbl.curr_enc_sw_smpl               ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(pwr_cbl.fault                          ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(pwr_cbl.dac_data                       ,FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(pwr_cbl.dac_steps                      ,FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(pwr_cbl.control_state                  ,FMSTR_TSA_UINT8 )
FMSTR_TSA_RW_VAR(pwr_cbl.dcdc_sync_freq                 ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(pwr_cbl.dcdc_mode                      ,FMSTR_TSA_UINT8 )

FMSTR_TSA_TABLE_END();

// Разделено на две таблицы поскольку помещение всех переменных в одну таблицу вызывало сбои в работе протокола во время считывания таблицы
FMSTR_TSA_TABLE_BEGIN(app_vars2)

FMSTR_TSA_RW_VAR(adcs.smpl_ACC_I                        ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(adcs.smpl_PSRC_I                       ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(adcs.smpl_LOAD_V                       ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(adcs.smpl_AIN2                         ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(adcs.smpl_VREF165                      ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(adcs.smpl_ACC_V                        ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(adcs.smpl_SYS_V                        ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(adcs.smpl_AIN3                         ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(adcs.smpl_AIN1                         ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(adcs.smpl_AIN4                         ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(adcs.smpl_TSENS                        ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(adcs.smpl_PSRC_V                       ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(adcs.smpl_LOAD_I                       ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(adcs.smpl_TERM                         ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(adcs.smpl_VREF                         ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(pst.OUT1                               ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(pst.OUT2                               ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(pst.OUT3                               ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(pst.OUT4                               ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(pst.LED_green                          ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(pst.LED_red                            ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(pst.ASW_R                              ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(pst.ASW_F                              ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(pst.PSW_R                              ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(pst.PSW_F                              ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(pst.LSW_F                              ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(pst.OLED_RES                           ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(pst.OLEDV                              ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(pst.OLED_DC                            ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(pst.OLED_CS                            ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(pst.EN_CHARGER                         ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(pst.DCDC_MODE                          ,FMSTR_TSA_UINT8)
FMSTR_TSA_RW_VAR(pst.DCDC_PGOOD                         ,FMSTR_TSA_UINT8)

FMSTR_TSA_RW_VAR(matlab_time_step                       ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(matlab_time_step_min                   ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(matlab_time_step_max                   ,FMSTR_TSA_UINT32)

FMSTR_TSA_TABLE_END();


FMSTR_TSA_TABLE_LIST_BEGIN()

FMSTR_TSA_TABLE(wvar_vars)
FMSTR_TSA_TABLE(app_vars)
FMSTR_TSA_TABLE(app_vars2)

FMSTR_TSA_TABLE_LIST_END()
